name: Deploy specific folder to Azure Web App - Ejendomsinvestor

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_FOLDER: "Øvelse 4 - HTTP"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm install/build/test (only in app folder)
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_81B99E2F9B084519B4EE6C37FA57023B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F571AA7906904CE2A4D60AE301D88528 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81F3D10CE672449E9B81C8FC8C3A77A3 }}

      - name: Deploy only the app folder
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Ejendomsinvestor"
          slot-name: "Production"
          package: ${{ env.APP_FOLDER }}